library("rjson")
sample <- fromJSON(file = "classified")
positive <- Filter(function(x) x$class == "positive", sample)
negative <- Filter(function(x) x$class == "negative", sample)
neutral <- Filter(function(x) x$class == "neutral", sample)
dummy <- Filter(function(x) x$class == "dummy", sample)

print(length(positive))
print(length(negative))
print(length(neutral))
print(length(dummy))
